### ISSUE TITLE
ASCII encode error while writing log file.

### ISSUE THREAD

**Issue by dangle** [contains-io/rcli#72]
On OSX with python 2.7, rcli throws an exception trying to encode unicode as ascii while writing the log file.

**Comment by dangle** [comment]
Traceback (most recent call last):
  File "/Users/nuno/.virtualenvs/testenv/bin/testenv", line 11, in <module>
    load_entry_point('testenv==0.2.1.dev5+ngd3fae4f.d20170512', 'console_scripts', 'testenv')()
  File "/Users/nuno/.virtualenvs/testenv/lib/python2.7/site-packages/rcli/dispatcher.py", line 83, in main
    return log.handle_unexpected_exception(e)
  File "/Users/nuno/.virtualenvs/testenv/lib/python2.7/site-packages/rcli/log.py", line 54, in handle_unexpected_exception
    write_logfile()
  File "/Users/nuno/.virtualenvs/testenv/lib/python2.7/site-packages/rcli/log.py", line 40, in write_logfile
    logfile.write(_LOGFILE_STREAM.getvalue())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 311796: ordinal not in range(128)
